package com.github.appreciated.demo;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.github.appreciated.circularprogressbar.CircularProgressBar;
import com.vaadin.ui.VerticalLayout;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class TestDesign extends VerticalLayout {
    protected CircularProgressBar progress1;
    protected CircularProgressBar progress2;
    protected CircularProgressBar progress3;
    protected CircularProgressBar progress4;

    public TestDesign() {
        Design.read(this);
    }
}
